# Generated by Django 3.2 on 2022-03-11 08:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_data',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 3, 11, 8, 11, 0, 487614, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client_data',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
