# Generated by Django 3.2 on 2022-03-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collector', '0002_auto_20220311_0911'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client_data',
            new_name='ClientData',
        ),
    ]
